/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * JFPesquisaApuracao.java
 *
 * Created on 19/09/2013, 17:09:20
 */
package Interfaces;

import Classes.Apuracao;
import ClassesDao.ApuracaoDAO;
import Excessoes.BancoException;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class BuscarResultadoParcial extends javax.swing.JFrame {

    /**
     * Creates new form JFPesquisaApuracao
     */
    public BuscarResultadoParcial(String telaPai) {
        initComponents();

        setLocationRelativeTo(null);


    }
    String parametroPesquisa = "";
    String campo;
    private String nomeApuracao = "teste não vai aparecer";
    private int codigoApuracao;

    public int getCodigoApuracao() {
        return codigoApuracao;
    }

    public void setCodigoApuracao(int codigoApuracao) {
        this.codigoApuracao = codigoApuracao;
    }

    public void setAcao(ActionListener parametro) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Candidatos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        masterTable.setModel(getDadosTabelaApuracaoPesquisa());
        masterTable.getTableHeader().setReorderingAllowed(false);
        masterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                masterTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(masterTable);

        jLabel1.setText("Total de votos:");

        jTextField1.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masterTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseReleased
        int linha = masterTable.getSelectedRow();
        codigoApuracao = masterTable.getValueAt(linha, 0).hashCode();
        //-----------nomeApuracao = ""+masterTable.getValueAt(linha, 1);
        nomeApuracao = "" + (masterTable.getValueAt(linha, 1));

    }//GEN-LAST:event_masterTableMouseReleased

    /**
     * @param args the command line arguments
     */
    public DefaultTableModel getDadosTabelaApuracaoPesquisa() {
        int totalVotos = 0;
        try {
            ApuracaoDAO dao = new ApuracaoDAO();
            List<Apuracao> lista = dao.pesquisaApuracao(parametroPesquisa, campo);

            Object[][] dados = new Object[lista.size()][3];

            for (int us = 0; us < lista.size(); us++) {
                totalVotos += lista.get(us).getContagem();
            }

            for (int us = 0; us < lista.size(); us++) {
                if (lista.get(us).getCodigo() == 0) {
                    dados[us][0] = "VOTOS EM BRANCO";
                } else if (lista.get(us).getCodigo() == 1) {
                    dados[us][0] = "VOTOS NULOS";
                } else {
                    dados[us][0] = lista.get(us).getCodigo();
                }

                dados[us][1] = lista.get(us).getContagem();
                if (lista.get(us).getContagem() == 0) {
                    dados[us][2] = "0 %";
                } else {
                    dados[us][2] = (lista.get(us).getContagem() * 100) / totalVotos + " %";
                }

            }
            jTextField1.setText(totalVotos + "");

            lista = null;
            dao.desconectar();
            String[] nomeColunas = {"Número", "Contagem parcial de votos", "Porcentagem"};
            return new DefaultTableModel(dados, nomeColunas);
        } catch (BancoException e) {
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }

    public String getNomeApuracao() {
        return nomeApuracao;
    }

    public void setNomeApuracao(String nomeApuracao) {
        this.nomeApuracao = nomeApuracao;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable masterTable;
    // End of variables declaration//GEN-END:variables
}
